### ISSUE TITLE
Workshop Infrastructure

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/rpharma2020_tidytranscriptomics#2]
Two options

**1) RTT** 
https://github.com/sol-eng/classroom-getting-started

Pros:

- Possibly easier to get resources (more RAM etc)
- Can have more complicated things e.g. Python (but we don't need that)

Cons:

- Can't install packages ourselves 

**2) RStudio Cloud** Instructor Plan (through RPharma)
https://rstudio.cloud/plans/instructor

Pros:

- Can install and update packages ourselves

Cons:

- **Must log out when not using** (or I think close browser tab might work) as otherwise it will keep using project hours. We get 160 hrs free then 20c per hour. But if using more RAM it use more project hours e.g. 3GB RAM uses 2 project hrs per hr of time
- Two people can't work on the same project at the same time,`[ see here](RStudio Cloud projects are great for collaboration, but note that two people cannot work on the project at the same time. So people will either need to take turns editing a project, or if your research group uses version control, they can of course use a service like GitHub for the collaboration aspect.)`. So we might need to have our own separate copies and then push/pull from the github workshop repo to keep in sync

**Comment by mblue9** [comment]
I edited your comment above just to add more info on the 2 options.

**RStudio Cloud Instructor Plan (through RPharma)**
This is how I got the RStuuio Cloud working for future ref. It might be possible to do some of these things in a simpler way e.g. connecting to the Git repo

1) Create a project* Create with git repo next time, see below.

2) Under the Project Settings, increase the default RAM for the project to 3GB, as shown in the screenshot here : https://community.rstudio.com/t/bioconductor-packages-fail-r4-0/81952/3
Otherwise tidybulk installation gets killed at if < 2GB and vignette building gets killed if < 3GB seems to be due to the deseq2 part.

2) Update rmarkdown as got knitr error with `build_vignettes=TRUE` without that

3) Install packages from GitHub to be specific about what versions we're using
```
install.packages('remotes')
remotes::install_github(c("stemangiola/tidybulk@v1.1.8", "stemangiola/tidygate@v0.2.8", "stemangiola/tidyseurat@v0.1.8", "stemangiola/tidyHeatmap@v1.1.5"))
remotes::install_github("stemangiola/rpharma2020_tidytranscriptomics", build_vignettes = TRUE)
```
Note: the vignettes don't seem to work in the cloud anyway get 404 error with the links generated by browseVignettes
```
library(rpharma2020tidytranscriptomics)
browseVignettes("rpharma2020tidytranscriptomics")
```

4) Link to Git repo for workshop - next time try creating the project from the Git repo as in screenshot below

![Screen Shot 2020-10-03 at 9 45 47 pm](https://user-images.githubusercontent.com/5591821/94990762-f01a1400-05c1-11eb-836b-29ba528d96f6.png)

Link the project to the rpharma git repo.
If you've logged into RStudio Cloud with your GitHub credentials apparently no need to add. I mostly followed the info [here](https://bren.zendesk.com/hc/en-us/articles/360015826731-How-to-connect-RStudio-Cloud-with-Github#:~:text=Create%20a%20new%20project%20in,connected%20to%20your%20Github%20repository.).
```
git config --global user.email "Your email"
git config --global user.name "Your name"
git config remote.origin.url git@github.com:stemangiola/rpharma2020_tidytranscriptomics.git
```

5) Pull the workshop repo content into the project

6) Test running the vignettes

7) In RStudio lcloud can make changes & commit to Github repo
Need to run `git push -u origin master` before can push to the git repo

8) Clean up files created in .Rproj_user after running vignettes
`rm -r .Rproj.user/*`
As running tidytranscriptomics.Rmd creates about 1GB in .Rproj.user/ and there's <3GB available, running it a couple of times can fill the space allowance for the project & start getting the error `Error in save(x, options, file = output) : error writing to connection` when trying to run any code e.g. see /cloud/project/ below
```
rstudio-user@application-2885089-deployment-7539311-tx49p:/cloud/project$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         125G   26G   99G  21% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/nvme0n1p1  125G   26G   99G  21% /opt/R
/dev/nbd14      2.7G  2.5G   66M  98% /cloud/project
/dev/nbd12      2.7G   23M  2.6G   1% /home/rstudio-user
shm              64M     0   64M   0% /dev/shm
/dev/nbd15      2.7G  4.4M  2.6G   1% /home/rstudio-user/.rstudio
/dev/nbd13      2.7G  1.3G  1.3G  51% /home/rstudio-user/R
tmpfs            16G  4.0K   16G   1% /etc/rstudio/license
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
```
Can see how much is being use in Terminal with 
`df -h`

**Comment by stemangiola** [comment]
> I edited your comment above just to add more info on the 2 options.

Ya I was thinking that's too good of a comment for being mine XD
